projects:
  Krapiva:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: g4vko6wptvbn3nl3qkcierft6e
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: eu-central-1
      endpoints:
        prod: >-
          https://ow3s2nryd5en3jsautzlgz77pu.appsync-api.eu-central-1.amazonaws.com/graphql
