backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "article"
    label: "Articles"
    folder: "src/pages/articles"
    create: true
    slug: "{{slug}}-{{day}}-{{month}}-{{year}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-template"}
      - {label: "Category", name: "category", widget: "select", options: ["reviews", "analitics", "discussions", "persons", "palces", "videos", "zins"], default: "reviews"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Authors", name: "authors", widget: "list"}
      - {label: Image, name: image, widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}